LIB := ./lib
CLASSES := ./classes

all: $(CLASSES)/AdventCoinMiner.class

$(CLASSES)/AdventCoinMiner.class: $(LIB)/AdventCoinMiner.java
	@mkdir -p $(CLASSES)
	javac -d $(CLASSES) $(LIB)/AdventCoinMiner.java
